---
apiVersion: k3d.io/v1alpha2
kind: Simple
servers: 1
agents: 1
image: rancher/k3s:v1.21.2-k3s1
network: cluster-network
kubeAPI:
    hostIP: '127.0.0.1'
    hostPort: '6443'
ports:
  - port: 80:32080
    nodeFilters:
      - loadbalancer
options:
  k3d:
    wait: true
    timeout: '60s'
  k3s:
    extraServerArgs:
      - --no-deploy=traefik
  kubeconfig:
    updateDefaultKubeconfig: false
    switchCurrentContext: false
