version: '3.9'

services:
  cluster:
    image: covik/local-k3s-cluster
    build:
      context: .
    container_name: local-k3s-cluster
    command:
      - 'bash'
      - '-c'
      - 'tail -f /dev/null'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock